stages:
  - build-nupkg
  - nuget-push

build-nupkg:
  stage: build-nupkg
  image: mcr.microsoft.com/dotnet/sdk:5.0
  script:
    - ./pack.sh $CI_COMMIT_TAG
  artifacts:
    paths:
      - nuget-build
  only:
    - /^publish-.*$/

nuget-push:
  stage: nuget-push
  image: mcr.microsoft.com/dotnet/sdk:5.0
  script:
    - dotnet nuget add source "https://nuget.tdrs.ro/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet nuget push "./nuget-build/*.nupkg" "./nuget-build/*.snupkg" --source gitlab
  only:
    - /^publish-.*$/
